FlowerClient/Controllers/CartController.cs
using BuisinessObjects.Models;
using DataAccess;
using FlowerClient.Models;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http.Headers;
using System.Text.Json;
using System.Text;

namespace FlowerClient.Controllers
{
    public class CartController : Controller
    {


        private HttpClient client = null;

        public CartController() { }

        public IList<CartItem> cart { get; set; }
        public decimal Total { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            cart = SessionExtensions.GetData<List<CartItem>>(HttpContext.Session, "cart");
            if (cart == null)
            {
                cart = new List<CartItem>();
            }
            Total = cart.Sum(i => i.FlowerBouquet.UnitPrice * i.Quantity);
            return View();
        }

        public async Task<IActionResult> OnGetBuyNow(int id)
        {
            var flowerBouquet = new FlowerBouquet();
            cart = SessionExtensions.GetData<List<CartItem>>(HttpContext.Session, "cart");
            client = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contentType);
            string FlowerBouquetApiUrl = "https://localhost:44344/api/FlowerBouquets/" + id;
            HttpResponseMessage response = await client.GetAsync(FlowerBouquetApiUrl);
            string strData = await response.Content.ReadAsStringAsync();
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            };
            var flowerBouquetObject = JsonSerializer.Deserialize<FlowerBouquet>(strData, options);
            if (flowerBouquetObject == null)
            {
                return NotFound();
            }
            if (cart == null)
            {
                cart = new List<CartItem>();
                cart.Add(new CartItem
                {
                    FlowerBouquet = flowerBouquetObject,
                    Quantity = 1
                });
                SessionExtensions.SetData(HttpContext.Session, "cart", cart);
            }
            else
            {
                int index = Exists(cart, id);
                if (index == -1)
                {
                    cart.Add(new CartItem
                    {
                        FlowerBouquet = flowerBouquetObject,
                        Quantity = 1
                    });
                }
                else
                {
                    cart[index].Quantity++;
                }
                SessionExtensions.SetData(HttpContext.Session, "cart", cart);
            }
            Total = cart.Sum(i => i.FlowerBouquet.UnitPrice * i.Quantity);
            return View();
        }

        public IActionResult OnGetDelete(int id)
        {
            cart = SessionExtensions.GetData<List<CartItem>>(HttpContext.Session, "cart");
            int index = Exists(cart, id);
            cart.RemoveAt(index);
            SessionExtensions.SetData(HttpContext.Session, "cart", cart);
            Total = cart.Sum(i => i.FlowerBouquet.UnitPrice * i.Quantity);
            return View();
        }

        public IActionResult OnPostUpdate(int[] quantities)
        {
            cart = SessionExtensions.GetData<List<CartItem>>(HttpContext.Session, "cart");
            for (var i = 0; i < cart.Count; i++)
            {
                cart[i].Quantity = quantities[i];
            }
            SessionExtensions.SetData(HttpContext.Session, "cart", cart);
            Total = cart.Sum(i => i.FlowerBouquet.UnitPrice * i.Quantity);
            return View();
        }

        public async Task<IActionResult> OnPostCheckout()
        {
            cart = SessionExtensions.GetData<List<CartItem>>(HttpContext.Session, "cart");
            if (cart == null)
            {
                cart = new List<CartItem>();
            }
            if (cart.Count == 0)
            {
                return View();
            }
            Total = cart.Sum(i => i.FlowerBouquet.UnitPrice * i.Quantity);
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            };
            client = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contentType);
            string OrderApiUrl = "https://localhost:44344/api/Orders";
            var customerId = HttpContext.Session.GetInt32("id");
            Random rand = new Random();
            int orderId = rand.Next(1, 5000);
            var order = new Order
            {
                OrderId = orderId,
                OrderDate = DateTime.Now,
                OrderStatus = "CheckedOut",
                ShippedDate = DateTime.Now.AddDays(1),
                CustomerId = customerId,
                Total = Total
            };
            var jsonObject = JsonSerializer.Serialize(order);
            HttpContent content = new StringContent(jsonObject, Encoding.UTF8, "application/json");
            HttpResponseMessage response = await client.PostAsync(OrderApiUrl, content);
            if (response.StatusCode == System.Net.HttpStatusCode.Created)
            {
                for (var i = 0; i < cart.Count(); i++)
                {
                    client = new HttpClient();
                    string OrderDetailApiUrl = "https://localhost:44344/api/OrderDetails";
                    var orderDetail = new OrderDetailModel
                    {
                        OrderId = orderId,
                        FlowerBouquetId = cart[i].FlowerBouquet.FlowerBouquetId,
                        Quantity = cart[i].Quantity,
                        Discount = 0,
                        UnitPrice = cart[i].Quantity * cart[i].FlowerBouquet.UnitPrice
                    };
                    jsonObject = JsonSerializer.Serialize(orderDetail);
                    content = new StringContent(jsonObject, Encoding.UTF8, "application/json");
                    response = await client.PostAsync(OrderDetailApiUrl, content);
                    if (response.StatusCode != System.Net.HttpStatusCode.OK)
                    {
                        return View();
                    }
                }
                for (var i = 0; i < cart.Count(); i++)
                {
                    cart.RemoveAt(i);
                    SessionExtensions.SetData(HttpContext.Session, "cart", cart);
                }
            }
            else
            {
                return View();
            }
            return RedirectToPage("./OrderHistory", new { id = customerId });
        }

        private int Exists(IList<CartItem> cart, int id)
        {
            for (var i = 0; i < cart.Count; i++)
            {
                if (cart[i].FlowerBouquet.FlowerBouquetId == id)
                {
                    return i;
                }
            }
            return -1;
        }
    }
}

FlowerClient/Controllers/FlowerBouquetsController.cs
using BuisinessObjects.Models;
using DataAccess;
using FlowerClient.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using System.Text.Json;



namespace FlowerClient.Controllers
{
    [Authorize]

    public class FlowerBouquetsController : Controller
    {
        public FlowerBouquetsController() { }


        
        public async Task<IActionResult> Index()
        {
            try
            {
                //HttpResponseMessage response = await FlowerClientUtils.ApiRequest(
                //   FlowerHttpMethod.GET,
                //   FlowerClientConfiguration.DefaultBaseApiUrl + "/FlowerBouquets");
                HttpResponseMessage responseMessage;
                string fetchUrl = FlowerClientConfiguration.DefaultBaseApiUrl + "/FlowerBouquets";


                if (!FlowerClientUtils.IsAdmin(User))
                {
                    string customerId = User.Claims.FirstOrDefault(claim => claim.Type.Equals(ClaimTypes.NameIdentifier)).Value;
                    fetchUrl += "/customer/" + customerId;
                }

                responseMessage = await FlowerClientUtils.ApiRequest(
                    FlowerHttpMethod.GET,
                    fetchUrl);

                if (responseMessage.IsSuccessStatusCode)
                {
                    //string strData = await responseMessage.Content.ReadAsStringAsync();
                    //var options = new JsonSerializerOptions
                    //{
                    //    PropertyNameCaseInsensitive = true,
                    //};
                    //IEnumerable<FlowerBouquet> flowers = System.Text.Json.JsonSerializer.Deserialize<IEnumerable<FlowerBouquet>>(strData, options);
                    IEnumerable<FlowerBouquet> flowers = await responseMessage.Content.ReadFromJsonAsync<IEnumerable<FlowerBouquet>>();
                    return View(flowers);
                }
                else if (responseMessage.StatusCode == System.Net.HttpStatusCode.Unauthorized)
                {
                    return RedirectToAction("Access", "Login");
                }
                else
                {
                    throw new Exception(await responseMessage.Content.ReadAsStringAsync());
                }


            }
            catch(Exception ex)
            {
                ViewData["FlowerBouquets"] = ex.Message;
                return View();
            }
        }
        private async Task<IEnumerable<Category>> GetCategories()
        {
            HttpResponseMessage response = await FlowerClientUtils.ApiRequest(
                FlowerHttpMethod.GET,
                FlowerClientConfiguration.DefaultBaseApiUrl + "/Categories");

            if (response.IsSuccessStatusCode)
            {
                IEnumerable<Category> categories =
                    await response.Content.ReadFromJsonAsync<IEnumerable<Category>>();
                return categories;
            }
            else if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
            {
                throw new Exception("Failed to get categories!");
            }
            else
            {
                throw new Exception(await response.Content.ReadAsStringAsync());
            }
        }

        private async Task<IEnumerable<Supplier>> GetSupplier()
        {
            HttpResponseMessage response = await FlowerClientUtils.ApiRequest(
                FlowerHttpMethod.GET,
                FlowerClientConfiguration.DefaultBaseApiUrl + "/Suppliers");

            if (response.IsSuccessStatusCode)
            {
                IEnumerable<Supplier> suppliers =
                    await response.Content.ReadFromJsonAsync<IEnumerable<Supplier>>();
                return suppliers;
            }
            else if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
            {
                throw new Exception("Failed supplier!");
            }
            else
            {
                throw new Exception(await response.Content.ReadAsStringAsync());
            }
        }

        [Authorize(Roles = "ADMIN")]


        // Flowers/Create by category and supplier
        public async Task<IActionResult> Create()
        {
            try
            {
                IEnumerable<Category> categories = await GetCategories();
                ViewData["CategoryId"] = new SelectList(categories, "CategoryId", "CategoryName");
                
                IEnumerable<Supplier> suppliers =  await GetSupplier();
                ViewData["SupplierId"] = new SelectList(suppliers, "SupplierId", "SupplierName");
                return View();
            }
            catch (Exception ex)
            {
                ViewData["FlowerBouquets"] = ex.Message;
                return View();
            }
        }



        // create flowerboquets 
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create([Bind("CategoryId,SupplierId,FlowerBouquetName,Description,UnitPrice,UnitsInStock,FlowerBouquetStatus")]FlowerBouquet flowerBouquet)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    IEnumerable<Category> categories = await GetCategories();
                    ViewData["CategoryId"] = new SelectList(categories, "CategoryId", "CategoryName");

                    IEnumerable<Supplier> suppliers = await GetSupplier();
                    ViewData["SupplierId"] = new SelectList(suppliers, "SupplierId", "SupplierName");
                   
                    HttpResponseMessage responseMessage = await FlowerClientUtils.ApiRequest(FlowerHttpMethod.POST, FlowerClientConfiguration.DefaultBaseApiUrl + "/FlowerBouquets", flowerBouquet);
                    if (responseMessage.IsSuccessStatusCode)
                    {
                        //string responBody = await responseMessage.Content.ReadAsStringAsync();
                        //FlowerBouquet newFlower = JsonConvert.DeserializeObject<FlowerBouquet>(responBody);
                        FlowerBouquet newFlower = await responseMessage.Content.ReadFromJsonAsync<FlowerBouquet>();
                        if (newFlower == null)
                        {
                            throw new Exception("Failed to create flower!!");
                        }
                    }
                    else if (responseMessage.StatusCode == System.Net.HttpStatusCode.Unauthorized)
                    {
                        return RedirectToAction("Access", "Login");
                    }
                    else
                    {
                        throw new Exception(await responseMessage.Content.ReadAsStringAsync());

                    }
                }
                catch(Exception ex)
                {
                    ViewData["FlowerBouquets"] = ex.Message; 
                    return View(flowerBouquet);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(flowerBouquet);
        }


        [Authorize(Roles = "ADMIN")]

        // Flowers/edit/1

        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if(id == null)
                {
                    throw new Exception("id doesn't sepicial");
                }
                HttpResponseMessage responseMessage = await FlowerClientUtils.ApiRequest(FlowerHttpMethod.GET, FlowerClientConfiguration.DefaultBaseApiUrl + "/FlowerBouquets/" + id);
                if (responseMessage.IsSuccessStatusCode)
                {
                    FlowerBouquet flowerBouquet = await responseMessage.Content.ReadFromJsonAsync<FlowerBouquet>();

                    //string responBody = await responseMessage.Content.ReadAsStringAsync();
                    //FlowerBouquet flowerBouquet = JsonConvert.DeserializeObject<FlowerBouquet>(responBody);
                    ViewData["CategoryId"] = new SelectList(await GetCategories(), "CategoryId", "CategoryName", flowerBouquet.CategoryId);
                    ViewData["SupplierId"] = new SelectList(await GetSupplier(), "SupplierId", "SupplierName", flowerBouquet.SupplierId);
                    return View(flowerBouquet);
                }
                else if (responseMessage.StatusCode == System.Net.HttpStatusCode.Unauthorized) 
                {
                    return RedirectToAction("Access", "Login");
                }else
                {
                    throw new Exception(await responseMessage.Content.ReadAsStringAsync());
                }
            }catch(Exception ex)
            {
                ViewData["FlowerBouquets"] = ex.Message;
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(int id, [Bind("FlowerBouquetId,CategoryId,FlowerBouquetName,Description,UnitPrice,UnitsInStock,FlowerBouquetStatus,SupplierId")] FlowerBouquet bouquet)
        {
            if (ModelState.IsValid)
            {
               
                try
                {
                    HttpResponseMessage responseMessage = await FlowerClientUtils.ApiRequest(FlowerHttpMethod.PUT, FlowerClientConfiguration.DefaultBaseApiUrl + "/FlowerBouquets/" + id, bouquet);

                    ViewData["CategoryId"] = new SelectList(await GetCategories(), "CategoryId", "CategoryName", bouquet.CategoryId);
                    ViewData["SupplierId"] = new SelectList(await GetSupplier(), "SupplierId", "SupplierName", bouquet.SupplierId);

                    if (responseMessage.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else if (responseMessage.StatusCode == System.Net.HttpStatusCode.Unauthorized)

FlowerClient/Views/FlowerBouquets/Cart.cshtml
@page
@model FlowerClient.Controllers.CartController;
@{
    ViewData["Title"] = "Your cart";
}
<h1>Your Cart</h1>

<p>
    <a asp-page="FlowerBouquets">Add New</a>
</p>
<form asp-action="Cart" asp-page-handler="update">
    <table class="table">
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Sub Total</th>
            <th></th>
        </tr>
        @foreach (var item in Model.cart)
        {
            <tr>
                <td>@item.FlowerBouquet.FlowerBouquetName</td>
                <td>$@item.FlowerBouquet.UnitPrice</td>
                <td><input type="number" name="quantities" value="@item.Quantity" min="1" style="width: 50px;" /></td>
                <td>
                    $@(item.FlowerBouquet.UnitPrice * item.Quantity)
                </td>
                <td>
                    <input class="btn btn-primary" type="submit" value="Update" /> |
                    <a style="color:red" asp-page="cart" asp-action-handler="delete" asp-route-id="@item.FlowerBouquet.FlowerBouquetId">Delete</a>
                </td>
            </tr>
        }
        <tr>
            <td colspan="6" align="right">Total</td>
            <td align="center">$@Model.Total</td>
        </tr>
    </table>
</form>
<form asp-controller="Cart" asp-action="cart" asp-page-handler="checkout">
    <input class="btn btn-success" type="submit" value="Checkout" />
</form>

FlowerClient/Views/FlowerBouquets/Create.cshtml
@model BuisinessObjects.Models.FlowerBouquet

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>FlowerBouquet</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="FlowerBouquetId" class="control-label"></label>
                <input asp-for="FlowerBouquetId" class="form-control" />
                <span asp-validation-for="FlowerBouquetId" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class ="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="FlowerBouquetName" class="control-label"></label>
                <input asp-for="FlowerBouquetName" class="form-control" />
                <span asp-validation-for="FlowerBouquetName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitPrice" class="control-label"></label>
                <input asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitsInStock" class="control-label"></label>
                <input asp-for="UnitsInStock" class="form-control" />
                <span asp-validation-for="UnitsInStock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlowerBouquetStatus" class="control-label"></label>
                <input asp-for="FlowerBouquetStatus" class="form-control" />
                <span asp-validation-for="FlowerBouquetStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SupplierId" class="control-label"></label>
                <select asp-for="SupplierId" class ="form-control" asp-items="ViewBag.SupplierId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@if (ViewData["FlowerBouquets"] != null)
{
    <div class="row ml-0 mr-0">
        <p class="text-danger">@ViewData["FlowerBouquets"]</p>
    </div>
}
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FlowerClient/Views/FlowerBouquets/Delete.cshtml
@model BuisinessObjects.Models.FlowerBouquet

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FlowerBouquet</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlowerBouquetName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlowerBouquetName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UnitsInStock)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitsInStock)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlowerBouquetStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlowerBouquetStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Supplier)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Supplier.SupplierId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="FlowerBouquetId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FlowerClient/Views/FlowerBouquets/Edit.cshtml
@model BuisinessObjects.Models.FlowerBouquet

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>FlowerBouquet</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FlowerBouquetId" />
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlowerBouquetName" class="control-label"></label>
                <input asp-for="FlowerBouquetName" class="form-control" />
                <span asp-validation-for="FlowerBouquetName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitPrice" class="control-label"></label>
                <input asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitsInStock" class="control-label"></label>
                <input asp-for="UnitsInStock" class="form-control" />
                <span asp-validation-for="UnitsInStock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlowerBouquetStatus" class="control-label"></label>
                <input asp-for="FlowerBouquetStatus" class="form-control" />
                <span asp-validation-for="FlowerBouquetStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SupplierId" class="control-label"></label>
                <select asp-for="SupplierId" class="form-control" asp-items="ViewBag.SupplierId"></select>
                <span asp-validation-for="SupplierId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
@if (ViewData["FlowerBouquets"] != null)
{
        <div class="row ml-0 mr-0">
        <p class="text-danger">@ViewData["FlowerBouquets"]</p>
        </div>
}
<div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FlowerClient/Views/FlowerBouquets/Index.cshtml
@model IEnumerable<BuisinessObjects.Models.FlowerBouquet>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FlowerBouquetName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UnitPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UnitsInStock)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlowerBouquetStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Supplier)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FlowerBouquetName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UnitPrice)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UnitsInStock)
                    </td>
                    <td>
                        @if(item.FlowerBouquetStatus == 0)
                    {

                        <button class="btn btn-danger">Deactivate</button>

                    }
                    else
                    {
                        <button class="btn btn-success">Activate</button>
                    }
                    </td>
                    
                    <td>
                        @Html.DisplayFor(modelItem => item.Category.CategoryName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Supplier.SupplierName)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.FlowerBouquetId">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.FlowerBouquetId">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.FlowerBouquetId">Delete</a>
                        <a asp-action="Cart" asp-route-id="@item.FlowerBouquetId">Cart</a>




                    </td>
                </tr>
            }
        }
    </tbody>
</table>
@if (TempData["FlowerBouquets"] != null)
{
    <p class="text-danger">@TempData["FlowerBouquets"] </p>
}